spring:
  profiles: board_gradle
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/board_gradle?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: sks0413

  mvc:
    view:
      prefix: /WEB-INF/view
      wuffix: .jsp